#package(default_visibility = ["//visibility:public"])

licenses(["notice"])

COPTS = ["-O2"]
LINKOPTS = ["-lpthread", "-ldl", "-lrt"]

cc_library(
    name = "eventbus",
    srcs = [
    ],
    hdrs = [
      "eventbus.h"
    ],
    deps = [
    ],
    copts = COPTS,
    linkopts = LINKOPTS,
    )
